### ISSUE TITLE
[REQ] Manual "hash to hash" patch rules for images without supported package managers

### ISSUE THREAD

**Issue by robert-cronin** [project-copacetic/copacetic#1033]
### What kind of request is this?

New feature

### What is your request or suggestion?

Copas current patch flow depends on the target image exposing a package manager (apk, dpkg, rpm) so it can:

1. locate an installed version (i.e. fixed version mapping) and
2. apply an update with dependency/backwards compatible safety

That leaves a gap for images that do not ship a conventional package manager (e.g. scratch images, tiny statically linked distroless builds, language specific buildpacks) or for scenarios where operators already know exactly which artifact hash remediates a CVE and simply want to swap it in

e.g. there might be a CVE that shows up for a non-packaged file when using rekor:

```
trivy image --sbom-sources rekor <image>
```

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by robert-cronin** [comment]
For this, we could have something like `copa patch -i <image> -m manual-rule.yaml` where we define a yaml schema like this:

```
target:
  path: /usr/local/bin/foo
  sha256: "a3b1…deadbeef"
replacement:
  source: registry.example.com/patches/foo-fixed:1.0
  internalPath: /bin/foo
  sha256: "9c55…cafefeed"
  mode: 0755
```
