### ISSUE TITLE
[BUG] `copa patch` panics (nil pointer in `connhelpers/docker.go`) with DinD+TLS on Kubernetes

### ISSUE THREAD

**Issue by caiolombello** [project-copacetic/copacetic#1047]
### Version of copa

v0.10.0

### Expected Behavior

When `DOCKER_HOST` points to a TLS-enabled DinD service, `copa patch` (without an explicit `--addr` for BuildKit) should either:
1. Successfully auto-discover and connect to the BuildKit instance within the DinD if `DOCKER_BUILDKIT=1` is set.
2. Or, provide a clear error message if it cannot establish a connection or if an explicit BuildKit address is required.

### Actual Behavior

When `copa patch` is run in a GitLab CI job on a Kubernetes runner with `DOCKER_HOST` pointing to a TLS-enabled DinD service (and `DOCKER_BUILDKIT=1`), and no explicit `--addr` is provided to `copa`, the tool panics with a "nil pointer dereference" error. The panic originates in `github.com/project-copacetic/copacetic/pkg/buildkit/connhelpers/docker.go`.

Stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc5ff54]
goroutine 47 [running]:
[github.com/cpuguy83/go-docker/transport.(*Transport).DoRaw(0xc000c50280](https://github.com/cpuguy83/go-docker/transport.(*Transport).DoRaw(0xc000c50280), {0x4184f88, 0xc000790300}, {0x35103ff, 0x4}, {0xc000c0a068, 0x5}, {0xc0009f4008, 0x1, 0x1})
/home/runner/go/pkg/mod/[github.com/cpuguy83/go-docker@v0.3.0/transport/transport.go:84](https://github.com/cpuguy83/go-docker@v0.3.0/transport/transport.go:84) +0x2f4
[github.com/project-copacetic/copacetic/pkg/buildkit.autoClient.Docker.func2](https://github.com/project-copacetic/copacetic/pkg/buildkit.autoClient.Docker.func2)({0x4184f88, 0xc000790300}, {0x413e110?, 0x35ca134?})
/home/runner/work/copacetic/copacetic/pkg/buildkit/connhelpers/docker.go:28 +0x151
google.golang.org/grpc/internal/transport.dial({0x4184f88, 0xc000790300}, 0xc0000944c0, {{0x35ca134, 0x1c}, {0x3529441, 0x9}, 0xc0000c4618, 0x0, {0x0, ...}}, ...)
/home/runner/go/pkg/mod/google.golang.org/grpc@v1.70.0/internal/transport/http2_client.go:171 +0x172
... (rest of stack trace)
```

### Steps To Reproduce

1. Set up a GitLab CI pipeline using a Kubernetes runner.
2. Configure a Docker-in-Docker (DinD) service (e.g., `docker:28.1.1-dind`) with TLS enabled.
   - Environment variables for the job:
     ```yaml
     DOCKER_HOST: tcp://docker:2376
     DOCKER_TLS_VERIFY: "1"
     DOCKER_TLS_CERTDIR: "/certs" # (certs correctly mounted and accessible)
     DOCKER_CERT_PATH: "/certs/client"
     DOCKER_BUILDKIT: "1"
     ```
3. In the job script:
   a. Load the target image into the DinD daemon: `docker load -i image.tar`
   b. Attempt to patch the image using `copa` without an explicit `--addr`:
      `copa patch -i <target-image-tag> -r vulnerabilities.json -o patched-image.tar --debug`
4. Observe the panic.

**Relevant Job Log**
[Job Log](https://github.com/user-attachments/files/20103581/Running.with.gitlab-runner.16.7.txt)

**Job definition**
```yaml
patch_vulnerabilities:
  stage: patch_vulnerabilities
  image: docker.io/sankhyaimages/devops-build-util:copacetic
  when:
  services:
    - name: docker:28.1.1-dind
      alias: docker
      command: 
        - "--feature"
        - "containerd-snapshotter=true"
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_DRIVER: overlayfs
    DOCKER_BUILDKIT: "1"
  script:
    - |
      echo "Carregando image no Docker daemon..."
      docker load -i image

      TAG="localhost/$CONTAINER_REPOSITORY_NAME:${NEXT_VERSION:-canary}"
      PATCHED_TAG="${TAG}-patched"

      echo "Aplicando patch na imagem..."
     
      copa patch \
        -i "$TAG" \
        -r os_vulns.json

      echo "Salvando imagem patchada..."
      docker save -o ./patched-image.tar "$PATCHED_TAG"

      echo "Verificando saída..."
      if [ ! -s ./patched-image.tar ]; then
        echo "ERRO: patched-image.tar não gerado" >&2;
        exit 1;
      fi
  artifacts:
    paths:
      - patched-image.tar
    expire_in: 1 hour
```

**Additional Context:**
This suggests an issue with how `copa`'s Docker client initialization or auto-discovery mechanism handles TLS-enabled Docker daemons when attempting to find a BuildKit endpoint, particularly in a Kubernetes DinD context. The underlying `go-docker` library seems to encounter a nil pointer during this process.

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.
