### ISSUE TITLE
[BUG] `copa patch` panics (nil pointer in `patch/patch.go`) with manual `buildkitd` (v0.12.4) via TCP

### ISSUE THREAD

**Issue by caiolombello** [project-copacetic/copacetic#1048]
### Version of copa

v0.10.0

### Expected Behavior

`copa patch` should successfully connect to a manually started `buildkitd` instance (version `moby/buildkit:v0.12.4`) over TCP (either insecurely or with mTLS configured) and perform the image patching.

### Actual Behavior

When `copa patch` is configured to connect to a manually started `buildkitd` container (version `moby/buildkit:v0.12.4`) via a TCP address (e.g., `--addr tcp://buildkitd:1234` or `--addr tcp://127.0.0.1:8888` with mTLS certs), it panics with a "nil pointer dereference" error. The panic originates in `github.com/project-copacetic/copacetic/pkg/patch/patch.go:299`.

Stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b7f88a]
goroutine 13 [running]: # (goroutine number may vary)
[github.com/project-copacetic/copacetic/pkg/patch.patchWithContext.func2](https://github.com/project-copacetic/copacetic/pkg/patch.patchWithContext.func2)()
/home/runner/work/copacetic/copacetic/pkg/patch/patch.go:299 +0x38a
golang.org/x/sync/errgroup.(*Group).Go.func1()
/home/runner/go/pkg/mod/golang.org/x/sync@v0.11.0/errgroup/errgroup.go:78 +0x50

... (rest of stack trace)
```

This panic occurred in two scenarios:
1. Connecting to `buildkitd` over an insecure TCP connection within a shared Docker network.
2. Connecting to `buildkitd` over a TCP connection secured with mTLS (certificates generated dynamically).

### Steps To Reproduce

**Scenario with insecure TCP and local registry**

1. Set up a GitLab CI job with a DinD service.
2. In the `before_script`:
   a. Create a Docker network (e.g., `buildnet`).
   b. Start a local Docker registry (e.g., `registry:2`) on `buildnet`.
   c. Load the target image, tag it, and push it to the local registry (e.g., `registry.local:5000/image:patched`).
   d. Start a `moby/buildkit:v0.12.4` container (named `buildkitd`) on `buildnet`, exposing its TCP port (e.g., `1234`) insecurely, and configured to use the local insecure registry.
     ```bash
     docker run -d --rm --privileged \
       --name buildkitd --network buildnet --entrypoint buildkitd \
       moby/buildkit:v0.12.4 \
       --addr tcp://0.0.0.0:1234 \
       --insecure-registry registry.local:5000
     ```
3. In the `script` section, run `copa patch`:
   `copa patch -i registry.local:5000/image:patched -r vulnerabilities.json -t "patched-fixed" --addr tcp://buildkitd:1234 --debug`
4. Observe the panic in `patch.go`.

**Scenario with mTLS**
1. Set up a GitLab CI job with a DinD service.
2. In the `before_script`:
   a. Dynamically generate TLS certificates (CA, daemon cert/key, client cert/key) using `openssl`.
   b. Start a `moby/buildkit:v0.12.4` container (named `buildkitd`), exposing its TCP port (e.g., `8888`) mapped to `127.0.0.1` on the job host. Configure `buildkitd` with the generated daemon TLS certs and CA.
     ```bash
     docker run --detach --rm --privileged -p 127.0.0.1:8888:8888/tcp \
       --name buildkitd --entrypoint buildkitd -v "$PWD/.certs:/etc/buildkit/certs" \
       "moby/buildkit:v0.12.4" \
       --addr tcp://0.0.0.0:8888 \
       --tlscacert /etc/buildkit/certs/daemon/ca.pem \ # Path to CA used by daemon
       --tlscert /etc/buildkit/certs/daemon/cert.pem \
       --tlskey /etc/buildkit/certs/daemon/key.pem
     ```
   c. Load the target image into the DinD daemon.
3. In the `script` section, run `copa patch`, providing the client mTLS certificates:
   `copa patch -i <target-image-tag> -r vulnerabilities.json -t "patched-fixed" --addr tcp://127.0.0.1:8888 --cacert .certs/ca.pem --cert .certs/client/cert.pem --key .certs/client/key.pem --debug`
4. Observe the panic in `patch.go`.

**Relevant Job Logs**

- [Insecure TCP + Local Registry logs](https://github.com/user-attachments/files/20103703/Running.with.gitlab-runner.16.7.txt)

**Job Definition
```yaml
patch_vulnerabilities:
  stage: patch_vulnerabilities
  image: docker.io/sankhyaimages/devops-build-util:copacetic
  services:
    - name: docker:28.1.1-dind
      alias: docker
      command: 
        - "--insecure-registry=registry.local:5000"
        - "--feature"
        - "containerd-snapshotter=true"
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_DRIVER: overlayfs
    DOCKER_BUILDKIT: "1"
    BUILDKIT_PORT: "1234"
    BUILDKIT_VERSION: "v0.12.4"
  before_script:
    - echo "Criando rede compartilhada..."
    - docker network create buildnet

    - echo "Subindo registry local..."
    - |
      docker run -d \
        --name registry \
        --network buildnet \
        registry:2

    - echo "Obtendo IP do registry e atualizando /etc/hosts..."
    - export REGISTRY_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' registry)
    - echo "$REGISTRY_IP registry.local" >> /etc/hosts

    - echo "Carregando e enviando imagem para o registry local..."
    - docker load -i image
    - docker tag localhost/$CONTAINER_REPOSITORY_NAME:${NEXT_VERSION:-canary} registry.local:5000/image:patched
    - docker push registry.local:5000/image:patched

    - echo "Subindo buildkitd na mesma rede..."
    - |
      docker run -d --rm --privileged \
        --name buildkitd \
        --network buildnet \
        --entrypoint buildkitd \
        moby/buildkit:$BUILDKIT_VERSION \
        --addr tcp://0.0.0.0:$BUILDKIT_PORT \
        --insecure-registry registry.local:5000

  script:
    - PATCHED_TAG="registry.local:5000/image:patched-fixed"

    - echo "Aplicando patch na imagem com Copacetic..."
    - |
      copa patch \
        -i registry.local:5000/image:patched \
        -r os_vulns.json \
        -t "patched-fixed" \
        --addr tcp://buildkitd:$BUILDKIT_PORT

    - echo "Pull da imagem patchada..."
    - docker pull "$PATCHED_TAG"

    - echo "Salvando imagem patchada..."
    - docker save -o ./patched-image.tar "$PATCHED_TAG"

    - echo "Verificando saída..."
    - |
      if [ ! -s ./patched-image.tar ]; then
        echo "ERRO: patched-image.tar não gerado" >&2;
        exit 1;
      fi

  artifacts:
    paths:
      - patched-image.tar
    expire_in: 1 hour
```

- [mTLS](https://github.com/user-attachments/files/20103721/Running.with.gitlab-runner.16.7.txt)

**Job Definition**
```yaml
patch_vulnerabilities:
  stage: patch_vulnerabilities
  image: docker.io/sankhyaimages/devops-build-util:copacetic
  services:
    - name: docker:28.1.1-dind
      alias: docker
      command:
        - "--feature"
        - "containerd-snapshotter=true"
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_DRIVER: overlayfs
    DOCKER_BUILDKIT: "1"
    BUILDKIT_PORT: "8888"
    BUILDKIT_VERSION: "v0.12.4"
  before_script:
    - echo "Gerando certificados TLS para BuildKit..."
    - |
      dnf install -y openssl
      mkdir -p .certs/daemon .certs/client

      # CA
      openssl genrsa -out .certs/ca-key.pem 4096
      openssl req -x509 -new -nodes -key .certs/ca-key.pem -sha256 -days 365 \
        -subj "/CN=BuildKit-CA" -out .certs/ca.pem

      # Daemon
      openssl genrsa -out .certs/daemon/key.pem 4096
      openssl req -new -key .certs/daemon/key.pem -subj "/CN=buildkitd" -out .certs/daemon/csr.pem
      openssl x509 -req -in .certs/daemon/csr.pem -CA .certs/ca.pem -CAkey .certs/ca-key.pem \
        -CAcreateserial -out .certs/daemon/cert.pem -days 365 -sha256

      # Client
      openssl genrsa -out .certs/client/key.pem 4096
      openssl req -new -key .certs/client/key.pem -subj "/CN=buildkit-client" -out .certs/client/csr.pem
      openssl x509 -req -in .certs/client/csr.pem -CA .certs/ca.pem -CAkey .certs/ca-key.pem \
        -CAcreateserial -out .certs/client/cert.pem -days 365 -sha256

    - echo "Subindo buildkitd com mTLS exposto via localhost..."
    - |
      docker run \
        --detach \
        --rm \
        --privileged \
        -p 127.0.0.1:$BUILDKIT_PORT:$BUILDKIT_PORT/tcp \
        --name buildkitd \
        --entrypoint buildkitd \
        -v "$PWD/.certs:/etc/buildkit/certs" \
        "moby/buildkit:$BUILDKIT_VERSION" \
        --addr tcp://0.0.0.0:$BUILDKIT_PORT \
        --tlscacert /etc/buildkit/certs/daemon/ca.pem \
        --tlscert /etc/buildkit/certs/daemon/cert.pem \
        --tlskey /etc/buildkit/certs/daemon/key.pem

    - echo "Carregando imagem para patch..."
    - docker load -i image

  script:
    - TAG="localhost/$CONTAINER_REPOSITORY_NAME:${NEXT_VERSION:-canary}"
    - PATCHED_TAG="${TAG}-patched"

    - echo "Aplicando patch com Copacetic via mTLS..."
    - |
      copa patch \
        -i "$TAG" \
        -r os_vulns.json \
        -t "${NEXT_VERSION:-canary}-patched" \
        --addr tcp://127.0.0.1:$BUILDKIT_PORT \
        --cacert .certs/ca.pem \
        --cert .certs/client/cert.pem \
        --key .certs/client/key.pem

    - echo "Salvando imagem patchada..."
    - docker save -o ./patched-image.tar "$PATCHED_TAG"

    - echo "Verificando saída..."
    - |
      if [ ! -s ./patched-image.tar ]; then
        echo "ERRO: patched-image.tar não gerado" >&2;
        exit 1;
      fi

  artifacts:
    paths:
      - patched-image.tar
    expire_in: 1 hour
```

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.
