### ISSUE TITLE
[REQ] bulk image patching

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#631]
### What kind of request is this?

New feature

### What is your request or suggestion?

Today, copa patches 1 image at a time. 

In the future, It might be useful for users to be able to declare a config that copa can read and bulk patch. Config will need some constraints such as starting tag, moving tag window, ability to ignore certain tags. 
This will be useful in recurring image patching scenarios.

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by ChristofferNissen** [comment]
+1 on the feature

In the meantime i have implemented something very similiar for helm charts as the source for images. Could be forked to consider different way to specify images [helmper](https://github.com/ChristofferNissen/helmper)

**Comment by amanycodes** [comment]
@sozercan I'll be taking this up, would be great if you could assign it as well.

**Comment by sozercan** [comment]
@amanycodes here's a starter config of roughly what I am thinking, can you start with a design doc? feel free to add or change things if it doesn't make sense, and we can review. I am fine scoping it to comprehensive patching (update all) or subset of this config below for now , but think about how we can extend with vuln reports and scanner plugins too.

```bash
copa patch --config copa-bulk-config.yaml ... 
```

```yaml
# copa-bulk-config.yaml
apiVersion: copa.sh/v1alpha1
kind: PatchConfig
metadata:
  description: "Bulk patching configuration for comprehensive patching"

# List of images to patch
images:
  # Example 1: Simple pattern-based tag discovery
  - name: "nginx"
    image: "docker.io/library/nginx"
    
    # Tag selection strategy
    tags:
      strategy: "pattern"              # Options: pattern, latest, list
      pattern: "^1\\.2[0-9]\\.[0-9]+$" # Match 1.20.x, 1.21.x, etc.
      maxTags: 3                       # Limit to 3 most recent matching tags (optional)
      exclude: ["1.20.0", "1.20.1"]   # Skip specific versions (optional)
      
    # Optional 
    # Where to put patched images
    target:
      # tag defaults to {{ .SourceTag }}-patched
      tag: "{{ .SourceTag }}-patched"  # Template: 1.21.6-patched
      
  # Example 2: Explicit tag list
  - name: "python"
    image: "docker.io/library/python"
    
    tags:
      strategy: "list"
      list: ["3.9.18", "3.10.13", "3.11.7"]  # Explicit list of tags
      
    # Optional
    # Override defaults for this image
    platforms: ["linux/amd64", "linux/arm64"]
      
  # Example 3: Latest tag only
  - name: "alpine"
    image: "docker.io/library/alpine"
    
    tags:
      strategy: "latest"               # Just patch the latest tag
      
  # Example 4: Pattern with constraints
  - name: "ubuntu"
    image: "docker.io/library/ubuntu"
    
    tags:
      strategy: "pattern"
      pattern: "^(20|22|24)\\.04$"     # LTS versions only
      exclude: ["20.04"]               # Skip older LTS
```
